### ISSUE TITLE
Contribution Guidelines and Other Questions

### ISSUE THREAD

**Issue by JKomoroski** [akiyosi/gonvim#5]
I'm interested in the gonvim project, and I'm glad to see someone has continued maintaining and adding to it. I do have a few questions for you:

- How does this project relate to the upstream?
- Do you ever plan to push your changes up?
- Should I make contributions to your project or to the upstream?
- Do you accept contributions?
- Are there any areas of the code base that need unit or integration tests?

**Comment by akiyosi** [comment]
Hi, 

> How does this project relate to the upstream?

This repository is upstream now.

> Do you ever plan to push your changes up?

Yes.

> Should I make contributions to your project or to the upstream?

Yes, contributions are welcome.

> Do you accept contributions?

Depending on the content of contribution, but I would like to exchange opinions and make it a better project.

> Are there any areas of the code base that need unit or integration tests?

Since the application works in conjunction with neovim, I have not been sufficiently considering which part of the test is useful. There are plans to implement tests in the future, but currently I add priority to feature addition. I welcome the contribution on test addition

**Comment by JKomoroski** [comment]
Thank you. I'll start poking around and see if there is anything I can work on.
